In [2]:
import pandas as pd
import numpy as np

In [3]:
train_csv = pd.read_csv('data/train.csv')

In [41]:
df = train_csv.groupby('eeg_id')[train_csv.columns[-6:]].agg('max') - train_csv.groupby('eeg_id')[train_csv.columns[-6:]].agg('min')
df['n_egg'] = train_csv.groupby('eeg_id')[['eeg_sub_id']].agg('count')
df[(df.iloc[:, :6] != 0).any(axis=1)]

,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote,n_egg
eeg_id,,,,,,,
11127485,1,0,1,0,0,0,9
19239792,1,0,0,0,0,1,14
20299905,0,1,0,0,0,1,32
21379701,2,3,0,1,0,2,18
21746311,10,0,0,0,0,2,9
...,...,...,...,...,...,...,...
4279656286,1,0,0,2,0,1,19
4282888597,0,0,0,8,0,0,26
4283246598,3,3,1,0,7,5,3
4284659653,1,10,0,6,1,2,32
4286085989,1,0,0,1,0,0,6

In [42]:
train_csv[train_csv['eeg_id'] == 4284659653]

,eeg_id,eeg_sub_id,eeg_label_offset_seconds,spectrogram_id,spectrogram_sub_id,spectrogram_label_offset_seconds,label_id,patient_id,expert_consensus,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote
90312,4284659653,0,0.0,1841034439,201,2696.0,2080594355,32481,Other,0,0,0,0,1,3
90313,4284659653,1,2.0,1841034439,202,2698.0,2127338458,32481,Other,0,0,0,0,1,3
90314,4284659653,2,8.0,1841034439,203,2704.0,2875503652,32481,Other,1,0,0,1,0,3
90315,4284659653,3,12.0,1841034439,204,2708.0,1175345073,32481,Other,1,0,0,1,0,3
90316,4284659653,4,18.0,1841034439,205,2714.0,2057846477,32481,Other,1,0,0,1,0,3
90317,4284659653,5,20.0,1841034439,206,2716.0,3134457521,32481,Other,1,0,0,1,0,3
90318,4284659653,6,26.0,1841034439,207,2722.0,2108559509,32481,Other,1,0,0,1,0,3
90319,4284659653,7,30.0,1841034439,208,2726.0,3370280515,32481,Other,1,0,0,1,0,3
90320,4284659653,8,34.0,1841034439,209,2730.0,3234110861,32481,Other,1,0,0,1,0,3
90321,4284659653,9,42.0,1841034439,210,2738.0,1746250238,32481,Other,1,0,0,1,0,2
90322,4284659653,10,46.0,1841034439,211,2742.0,1786807812,32481,Other,1,0,0,1,0,2
90323,4284659653,11,54.0,1841034439,212,2750.0,4284231588,32481,Seizure,1,1,0,0,0,1
90324,4284659653,12,56.0,1841034439,213,2752.0,2085337590,32481,Seizure,1,1,0,0,0,1
90325,4284659653,13,58.0,1841034439,214,2754.0,2481512933,32481,Seizure,1,1,0,0,0,1
90326,4284659653,14,70.0,1841034439,215,2766.0,2653269667,32481,LPD,0,10,0,0,0,1
90327,4284659653,15,78.0,1841034439,216,2774.0,4007549141,32481,LPD,0,10,0,0,0,1
90328,4284659653,16,80.0,1841034439,217,2776.0,641418024,32481,LPD,0,10,0,0,0,1
90329,4284659653,17,90.0,1841034439,218,2786.0,494497468,32481,LPD,0,10,0,0,0,1
90330,4284659653,18,96.0,1841034439,219,2792.0,2144853372,32481,LPD,0,10,0,0,0,1
90331,4284659653,19,98.0,1841034439,220,2794.0,1327082760,32481,LPD,0,10,0,0,0,1
90332,4284659653,20,114.0,1841034439,221,2810.0,4211041748,32481,LPD,0,10,0,0,0,1
90333,4284659653,21,122.0,1841034439,222,2818.0,662086826,32481,LPD,0,10,0,0,0,1
90334,4284659653,22,138.0,1841034439,223,2834.0,1899929058,32481,LPD,0,10,0,0,0,1
90335,4284659653,23,160.0,1841034439,224,2856.0,3430915355,32481,LRDA,0,4,0,6,0,3
90336,4284659653,24,162.0,1841034439,225,2858.0,67790176,32481,LRDA,0,4,0,6,0,3
90337,4284659653,25,164.0,1841034439,226,2860.0,1297592876,32481,LRDA,0,4,0,6,0,3
90338,4284659653,26,166.0,1841034439,227,2862.0,2977649588,32481,LRDA,0,4,0,6,0,3
90339,4284659653,27,170.0,1841034439,228,2866.0,2619891074,32481,LRDA,0,0,0,2,0,1
90340,4284659653,28,172.0,1841034439,229,2868.0,2529265436,32481,LRDA,0,0,0,2,0,1
90341,4284659653,29,174.0,1841034439,230,2870.0,731606228,32481,LRDA,0,0,0,2,0,1
90342,4284659653,30,176.0,1841034439,231,2872.0,4083734911,32481,LRDA,0,0,0,2,0,1
90343,4284659653,31,188.0,1841034439,232,2884.0,885118447,32481,LRDA,0,0,0,1,0,1

In [43]:
eeg = pd.read_parquet('data/train_eegs/3910994355.parquet')
eeg

,Fp1,F3,C3,P3,F7,T3,T5,O1,Fz,Cz,Pz,Fp2,F4,C4,P4,F8,T4,T6,O2,EKG
0,-36.509998,-45.439999,-46.259998,-19.670000,-27.709999,-29.430000,-14.360000,-5.910000,-32.150002,-43.099998,-13.780000,-30.410000,-31.160000,-13.200000,11.490000,-16.370001,76.209999,63.570000,24.620001,-12.830000
1,-37.849998,-47.910000,-47.660000,-23.170000,-31.200001,-30.700001,-16.520000,-7.220000,-37.820000,-47.150002,-15.560000,-30.059999,-33.000000,-15.410000,12.520000,-21.180000,73.790001,70.620003,26.030001,-8.260000
2,-42.759998,-47.349998,-44.880001,-16.170000,-33.400002,-27.639999,-15.740000,-4.940000,-34.560001,-44.369999,-14.030000,-31.580000,-33.880001,-17.200001,14.990000,-24.360001,75.050003,79.290001,30.559999,-11.950000
3,-46.750000,-48.060001,-41.169998,-10.620000,-33.529999,-26.260000,-11.470000,2.370000,-36.130001,-38.049999,-8.410000,-33.630001,-31.730000,-12.980000,19.530001,-27.160000,73.570000,84.239998,37.820000,-16.090000
4,-44.099998,-41.540001,-32.369999,-2.900000,-32.549999,-20.650000,1.190000,17.180000,-31.840000,-31.120001,1.750000,-33.660000,-25.600000,-7.820000,27.180000,-30.040001,61.889999,83.389999,44.509998,-7.920000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,51.299999,56.709999,56.770000,48.150002,50.549999,61.509998,52.220001,42.139999,50.070000,48.580002,33.939999,42.549999,38.310001,21.680000,-3.940000,18.820000,-54.830002,-78.150002,0.270000,26.070000
9996,59.910000,65.040001,63.209999,53.840000,55.320000,66.930000,58.560001,48.919998,59.720001,58.689999,40.790001,49.730000,45.799999,27.400000,0.450000,21.370001,-51.840000,-80.129997,5.480000,21.809999
9997,59.779999,69.620003,64.550003,53.169998,58.009998,67.459999,53.470001,45.810001,63.740002,61.360001,42.259998,55.630001,48.020000,31.240000,2.750000,23.280001,-48.930000,-80.269997,6.720000,15.530000
9998,68.050003,69.720001,64.019997,51.930000,62.599998,67.690002,50.459999,41.720001,60.299999,61.189999,44.250000,57.029999,46.599998,31.250000,5.530000,25.770000,-45.009998,-77.529999,4.750000,9.850000
9999,61.389999,66.029999,63.549999,52.299999,58.970001,66.120003,45.529999,38.930000,56.919998,59.570000,46.740002,53.990002,42.910000,32.240002,13.350000,23.830000,-39.270000,-67.949997,7.130000,11.820000

In [44]:
spg = pd.read_parquet('data/train_spectrograms/2146798838.parquet')
spg

,time,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
0,1,41.520000,40.299999,46.910000,15.580000,16.450001,21.290001,16.980000,29.879999,35.259998,...,0.39,0.40,0.47,0.48,0.49,0.65,0.67,0.53,0.60,0.48
1,3,83.599998,105.529999,144.729996,200.690002,219.919998,211.979996,186.399994,120.940002,71.540001,...,0.51,0.44,0.80,0.81,0.96,1.09,1.39,1.23,0.86,1.02
2,5,259.890015,305.269989,301.640015,159.750000,142.089996,95.519997,68.360001,58.200001,59.869999,...,0.53,0.48,0.61,0.83,0.82,1.28,1.29,0.90,0.85,0.60
3,7,163.410004,232.970001,183.610001,137.210007,79.330002,61.939999,37.270000,34.980000,29.480000,...,0.52,0.46,0.56,0.35,0.48,0.45,0.51,0.59,0.38,0.45
4,9,30.020000,57.810001,62.580002,54.669998,47.930000,23.799999,21.780001,16.440001,18.959999,...,0.77,0.67,0.54,0.49,0.60,0.52,0.48,0.54,0.60,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,753,2.910000,4.330000,5.610000,9.700000,12.300000,11.990000,10.900000,6.640000,3.990000,...,0.27,0.26,0.39,0.46,0.43,0.44,0.39,0.22,0.14,0.13
377,755,4.080000,4.730000,5.760000,10.210000,11.290000,13.140000,12.090000,13.390000,11.310000,...,0.25,0.33,0.27,0.36,0.44,0.38,0.33,0.26,0.25,0.22
378,757,2.870000,4.430000,5.900000,6.070000,5.960000,5.900000,3.210000,4.600000,2.380000,...,0.17,0.22,0.24,0.26,0.30,0.24,0.20,0.17,0.12,0.22
379,759,4.760000,8.980000,11.440000,12.480000,13.020000,9.560000,5.310000,3.280000,1.740000,...,0.21,0.25,0.27,0.24,0.28,0.24,0.29,0.23,0.30,0.26
380,761,3.890000,6.240000,7.920000,10.210000,8.770000,7.180000,5.720000,2.730000,1.790000,...,0.22,0.18,0.19,0.37,0.30,0.47,0.57,0.56,0.51,0.43

In [45]:
def eeg_window(row, eeg_path='data/train_eegs/'):
    eeg_data = pd.read_parquet(f'{eeg_path}{row.eeg_id}.parquet')
    eeg_offset = int(row.eeg_label_offset_seconds)
    eeg = eeg_data.iloc[(200 * eeg_offset):(200 * (eeg_offset + 50))]
    return eeg

eeg_window(train_csv.iloc[0])

,Fp1,F3,C3,P3,F7,T3,T5,O1,Fz,Cz,Pz,Fp2,F4,C4,P4,F8,T4,T6,O2,EKG
0,-80.519997,-70.540001,-80.110001,-108.750000,-120.330002,-88.620003,-101.750000,-104.489998,-99.129997,-90.389999,-97.040001,-77.989998,-88.830002,-112.120003,-108.110001,-95.949997,-98.360001,-121.730003,-106.449997,7.920000
1,-80.449997,-70.330002,-81.760002,-107.669998,-120.769997,-90.820000,-104.260002,-99.730003,-99.070000,-92.290001,-96.019997,-84.500000,-84.989998,-115.610001,-103.860001,-97.470001,-89.290001,-115.500000,-102.059998,29.219999
2,-80.209999,-75.870003,-82.050003,-106.010002,-117.500000,-87.489998,-99.589996,-96.820000,-119.680000,-99.360001,-91.110001,-99.440002,-104.589996,-127.529999,-113.349998,-95.870003,-96.019997,-123.879997,-105.790001,45.740002
3,-84.709999,-75.339996,-87.480003,-108.970001,-121.410004,-94.750000,-105.370003,-100.279999,-113.839996,-102.059998,-95.040001,-99.230003,-101.220001,-125.769997,-111.889999,-97.459999,-97.180000,-128.940002,-109.889999,83.870003
4,-90.570000,-80.790001,-93.000000,-113.870003,-129.960007,-102.860001,-118.599998,-101.099998,-107.660004,-102.339996,-98.510002,-95.300003,-88.930000,-115.639999,-99.800003,-97.500000,-88.730003,-114.849998,-100.250000,97.769997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-140.039993,-128.100006,-137.339996,-160.830002,-153.630005,-136.279999,-137.009995,-93.349998,-145.130005,-155.830002,-124.650002,-123.250000,-127.709999,-169.759995,-68.489998,-117.669998,-69.239998,-115.309998,-123.860001,65.010002
9996,-152.169998,-161.449997,-173.210007,-165.320007,-143.570007,-124.150002,-127.339996,-87.309998,-160.919998,-158.360001,-121.870003,-129.550003,-121.470001,-120.339996,-68.029999,-135.130005,-105.190002,-114.330002,-121.029999,47.090000
9997,-149.619995,-147.479996,-171.960007,-152.589996,-137.279999,-105.550003,-122.220001,-80.010002,-156.039993,-155.119995,-116.360001,-118.099998,-113.690002,-102.760002,-67.839996,-120.410004,-109.099998,-116.419998,-119.099998,95.589996
9998,-126.860001,-122.889999,-125.879997,-130.339996,-134.779999,-134.350006,-127.080002,-76.739998,-137.649994,-146.800003,-111.720001,-114.199997,-106.739998,-104.699997,-60.240002,-154.119995,-129.639999,-110.029999,-116.239998,72.980003
9999,-131.339996,-153.470001,-168.320007,-155.339996,-123.169998,-82.660004,-122.050003,-77.889999,-148.979996,-149.880005,-112.050003,-112.910004,-102.180000,-71.809998,-56.290001,-133.979996,-148.220001,-108.330002,-114.339996,25.549999

In [46]:
def spg_window(row, spg_path='data/train_spectrograms/'):
    spg_data = pd.read_parquet(f'{spg_path}{row.spectrogram_id}.parquet')
    spg_offset = int(row.spectrogram_label_offset_seconds)
    spg = spg_data.loc[(spg_data.time >= spg_offset) & (spg_data.time < spg_offset + 600)]
    return spg

spg_window(train_csv.iloc[0])

,time,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
0,1,4.26,10.98,9.05,13.65,11.49,8.930000,18.840000,19.260000,19.240000,...,0.31,0.17,0.28,0.19,0.24,0.27,0.29,0.16,0.22,0.19
1,3,2.65,3.97,12.18,13.26,14.21,13.230000,9.650000,8.110000,11.280000,...,0.15,0.13,0.14,0.24,0.24,0.36,0.35,0.31,0.36,0.40
2,5,4.18,4.53,8.77,14.26,13.36,16.559999,19.219999,17.510000,22.650000,...,0.29,0.21,0.16,0.25,0.28,0.28,0.34,0.48,0.44,0.48
3,7,2.41,3.21,4.92,8.07,5.97,12.420000,10.820000,14.960000,21.809999,...,0.33,0.51,0.49,0.64,0.58,0.42,0.32,0.31,0.32,0.33
4,9,2.29,2.44,2.77,4.62,5.39,7.080000,9.840000,12.270000,14.410000,...,0.44,0.38,0.48,0.63,0.45,0.45,0.49,0.33,0.31,0.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,591,5.26,7.41,10.16,7.25,15.35,27.590000,28.650000,27.600000,30.690001,...,0.09,0.17,0.11,0.09,0.10,0.08,0.07,0.17,0.17,0.24
296,593,5.17,7.17,10.05,13.47,13.22,11.560000,29.790001,24.660000,23.379999,...,0.06,0.06,0.05,0.11,0.09,0.08,0.16,0.21,0.20,0.20
297,595,1.87,3.59,8.69,7.59,8.33,11.880000,12.690000,16.360001,24.240000,...,0.09,0.07,0.07,0.06,0.06,0.07,0.08,0.10,0.10,0.10
298,597,3.27,5.63,9.46,11.19,11.98,12.260000,9.240000,7.030000,8.660000,...,0.12,0.08,0.06,0.04,0.04,0.06,0.05,0.08,0.13,0.14
299,599,4.18,5.85,7.22,16.25,15.41,13.340000,16.809999,12.640000,14.350000,...,0.11,0.15,0.07,0.08,0.12,0.17,0.23,0.25,0.17,0.15

In [47]:
from pathlib import Path

def dict_from_dir(path):
    parquet_files = Path(path).glob('*.parquet')
    data_dict = {int(file.stem): pd.read_parquet(file) for file in parquet_files}
    return data_dict

# eeg_dict = dict_from_dir(path='data/train_eegs/')
# spg_dict = dict_from_dir(path='data/train_spectrograms/')
# sum(df.memory_usage(deep=True).sum() for df in eeg_dict.values()) / (2**30), sum(df.memory_usage(deep=True).sum() for df in spg_dict.values()) / (2**30)

In [48]:
test_csv = pd.read_csv('data/test.csv')
test_csv.head()

   spectrogram_id      eeg_id  patient_id
0          853520  3911565283        6885

In [79]:
df = train_csv.groupby('eeg_id')[['eeg_id']].agg('count')
df.columns = ['eeg_count']
df.sort_values('eeg_count', ascending=False)

In [50]:
train_csv.groupby('eeg_id').agg('first').sort_values('spectrogram_id')

,eeg_sub_id,eeg_label_offset_seconds,spectrogram_id,spectrogram_sub_id,spectrogram_label_offset_seconds,label_id,patient_id,expert_consensus,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote
eeg_id,,,,,,,,,,,,,,
1628180742,0,0.0,353733,0,0.0,127492639,42516,Seizure,3,0,0,0,0,0
2277392603,0,0.0,924234,0,0.0,1978807404,30539,GPD,0,0,5,0,1,5
722738444,0,0.0,999431,0,0.0,557980729,56885,LRDA,0,1,0,14,0,1
387987538,0,0.0,1084844,0,0.0,4099147263,4264,LRDA,0,0,0,3,0,0
2529955608,0,0.0,1219001,4,190.0,4265493714,23435,Seizure,3,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1850739625,0,0.0,2146798838,3,162.0,2394534310,28488,LPD,0,9,0,2,0,7
3910994355,0,0.0,2146798838,0,0.0,4272062867,28488,LPD,0,9,0,2,0,7
3938393892,0,0.0,2146798838,1,60.0,2587113091,28488,LPD,0,9,0,2,0,7
1306668185,0,0.0,2147312808,0,0.0,1216355904,57480,LPD,0,3,0,0,0,0
351917269,0,0.0,2147388374,0,0.0,429140316,10351,LRDA,0,0,0,3,0,0

In [51]:
df = train_csv.copy()
TARGETS = df.columns[-6:]
TARGETS

Index(['seizure_vote', 'lpd_vote', 'gpd_vote', 'lrda_vote', 'grda_vote',
       'other_vote'],
      dtype='object')

In [52]:
train = df.groupby('eeg_id')[['spectrogram_id', 'spectrogram_label_offset_seconds']].agg({'spectrogram_id': 'first', 'spectrogram_label_offset_seconds': 'min'})
train.columns = ['spg_id', 'min']
spg_max = df.groupby('eeg_id')[['spectrogram_id', 'spectrogram_label_offset_seconds']].agg({'spectrogram_label_offset_seconds': 'max'})
train['max'] = spg_max

patient_ids = df.groupby('eeg_id')[['patient_id']].agg('first')
train['patient_id'] = patient_ids

y_data = df.groupby('eeg_id')[TARGETS].agg('sum').values
y_data = y_data / y_data.sum(axis=1, keepdims=True)
train[TARGETS] = y_data

tmp = df.groupby('eeg_id')[['expert_consensus']].agg('first')
train['target'] = tmp

train = train.reset_index()
train

,eeg_id,spg_id,min,max,patient_id,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote,target
0,568657,789577333,0.0,16.0,20654,0.0,0.000000,0.25,0.000000,0.166667,0.583333,Other
1,582999,1552638400,0.0,38.0,20230,0.0,0.857143,0.00,0.071429,0.000000,0.071429,LPD
2,642382,14960202,1008.0,1032.0,5955,0.0,0.000000,0.00,0.000000,0.000000,1.000000,Other
3,751790,618728447,908.0,908.0,38549,0.0,0.000000,1.00,0.000000,0.000000,0.000000,GPD
4,778705,52296320,0.0,0.0,40955,0.0,0.000000,0.00,0.000000,0.000000,1.000000,Other
...,...,...,...,...,...,...,...,...,...,...,...,...
17084,4293354003,1188113564,0.0,0.0,16610,0.0,0.000000,0.00,0.000000,0.500000,0.500000,GRDA
17085,4293843368,1549502620,0.0,0.0,15065,0.0,0.000000,0.00,0.000000,0.500000,0.500000,GRDA
17086,4294455489,2105480289,0.0,0.0,56,0.0,0.000000,0.00,0.000000,0.000000,1.000000,Other
17087,4294858825,657299228,0.0,12.0,4312,0.0,0.000000,0.00,0.000000,0.066667,0.933333,Other
17088,4294958358,260520016,2508.0,2508.0,25986,0.0,0.000000,0.00,0.000000,0.000000,1.000000,Other

In [53]:
from collections import Counter
target_votes = Counter(list(train_csv['expert_consensus']))
# target_votes = {f"{k.lower()}_vote":v for k,v in target_votes.items()}
# total_votes = sum([v for _,v in target_votes.items()])
# mean_vote_ratio = {k:(target_votes[k]/total_votes) for k,target in target_votes.items()}
# mean_vote_ratio
target_votes

Counter({'Seizure': 20933,
         'GRDA': 18861,
         'Other': 18808,
         'GPD': 16702,
         'LRDA': 16640,
         'LPD': 14856})

In [54]:
Counter(list(train_csv['expert_consensus']))

Counter({'Seizure': 20933,
         'GRDA': 18861,
         'Other': 18808,
         'GPD': 16702,
         'LRDA': 16640,
         'LPD': 14856})

In [55]:
train_csv['expert_consensus'].value_counts() / sum(train_csv['expert_consensus'].value_counts())

expert_consensus
Seizure    0.196002
GRDA       0.176601
Other      0.176105
GPD        0.156386
LRDA       0.155805
LPD        0.139101
Name: count, dtype: float64

In [4]:
# different eeg sub windows in different eeg windows, but all in the same spectrogram window

train_csv[train_csv['eeg_id'].isin([1850739625, 3910994355, 3938393892]) ]

,eeg_id,eeg_sub_id,eeg_label_offset_seconds,spectrogram_id,spectrogram_sub_id,spectrogram_label_offset_seconds,label_id,patient_id,expert_consensus,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote
106780,3910994355,0,0.0,2146798838,0,0.0,4272062867,28488,LPD,0,9,0,2,0,7
106781,3938393892,0,0.0,2146798838,1,60.0,2587113091,28488,LPD,0,9,0,2,0,7
106782,3938393892,1,4.0,2146798838,2,64.0,827904671,28488,LPD,0,9,0,2,0,7
106783,1850739625,0,0.0,2146798838,3,162.0,2394534310,28488,LPD,0,9,0,2,0,7

In [9]:
# Example of NaNs in raw data

pd.read_parquet(f'data/train_spectrograms/9661509.parquet').iloc[170:180]

,time,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
170,341,66.430000,70.080002,115.089996,101.849998,107.839996,136.889999,111.959999,115.010002,79.309998,...,0.79,0.78,0.90,0.58,0.41,0.43,0.73,0.80,0.82,0.86
171,343,17.660000,52.090000,55.070000,94.610001,105.809998,76.220001,64.790001,51.369999,28.070000,...,0.96,0.90,0.88,0.79,0.72,0.60,0.71,0.68,0.87,0.73
172,345,30.770000,59.889999,112.000000,154.389999,166.550003,163.259995,97.080002,51.939999,28.450001,...,0.90,0.84,0.82,0.40,0.80,0.87,0.90,0.87,0.65,0.63
173,347,11.940000,12.860000,58.639999,135.259995,156.429993,160.270004,147.300003,51.330002,27.190001,...,1.15,1.23,0.81,0.58,0.42,0.60,0.81,0.73,0.69,0.56
174,349,165.220001,228.190002,265.929993,284.350006,270.809998,205.300003,176.279999,126.639999,116.639999,...,1.23,1.04,0.69,0.59,0.48,0.46,0.74,0.79,0.73,0.70
175,351,291.980011,321.059998,419.470001,320.529999,223.350006,211.839996,150.179993,142.380005,161.149994,...,0.61,0.86,0.53,0.83,0.47,0.37,0.46,0.30,0.60,0.41
176,353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# check if there is any eeg_id mapped to more than one spectrogram_ids or patient_ids - confirmed to be none

train_csv.groupby('eeg_id')[['eeg_label_offset_seconds', 'spectrogram_id', 'spectrogram_label_offset_seconds', 'patient_id']].agg('nunique').describe()

,eeg_label_offset_seconds,spectrogram_id,spectrogram_label_offset_seconds,patient_id
count,17089.000000,17089.0,17089.000000,17089.0
mean,6.249634,1.0,6.249634,1.0
std,17.197882,0.0,17.197882,0.0
min,1.000000,1.0,1.000000,1.0
25%,1.000000,1.0,1.000000,1.0
50%,3.000000,1.0,3.000000,1.0
75%,6.000000,1.0,6.000000,1.0
max,743.000000,1.0,743.000000,1.0