In [1]:
import pandas as pd
import numpy as np

In [2]:
train_csv = pd.read_csv('data/train.csv')

In [3]:
def read_parquet_cache(path):
    cache = {}

    def read_parquet(id_):
        if id_ not in cache:
            cache[id_] = pd.read_parquet(f'{path}{id_}.parquet')
        return cache[id_]

    return read_parquet

read_eeg = read_parquet_cache(path='data/train_eegs/')
read_spg = read_parquet_cache(path='data/train_spectrograms/')

In [4]:
def eeg_window(row):
    eeg_data = read_eeg(row.eeg_id)
    eeg_offset = int(row.eeg_label_offset_seconds)
    eeg = eeg_data.iloc[(200 * eeg_offset):(200 * (eeg_offset + 50))]
    return eeg

eeg_window(train_csv.iloc[0])

,Fp1,F3,C3,P3,F7,T3,T5,O1,Fz,Cz,Pz,Fp2,F4,C4,P4,F8,T4,T6,O2,EKG
0,-80.519997,-70.540001,-80.110001,-108.750000,-120.330002,-88.620003,-101.750000,-104.489998,-99.129997,-90.389999,-97.040001,-77.989998,-88.830002,-112.120003,-108.110001,-95.949997,-98.360001,-121.730003,-106.449997,7.920000
1,-80.449997,-70.330002,-81.760002,-107.669998,-120.769997,-90.820000,-104.260002,-99.730003,-99.070000,-92.290001,-96.019997,-84.500000,-84.989998,-115.610001,-103.860001,-97.470001,-89.290001,-115.500000,-102.059998,29.219999
2,-80.209999,-75.870003,-82.050003,-106.010002,-117.500000,-87.489998,-99.589996,-96.820000,-119.680000,-99.360001,-91.110001,-99.440002,-104.589996,-127.529999,-113.349998,-95.870003,-96.019997,-123.879997,-105.790001,45.740002
3,-84.709999,-75.339996,-87.480003,-108.970001,-121.410004,-94.750000,-105.370003,-100.279999,-113.839996,-102.059998,-95.040001,-99.230003,-101.220001,-125.769997,-111.889999,-97.459999,-97.180000,-128.940002,-109.889999,83.870003
4,-90.570000,-80.790001,-93.000000,-113.870003,-129.960007,-102.860001,-118.599998,-101.099998,-107.660004,-102.339996,-98.510002,-95.300003,-88.930000,-115.639999,-99.800003,-97.500000,-88.730003,-114.849998,-100.250000,97.769997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-140.039993,-128.100006,-137.339996,-160.830002,-153.630005,-136.279999,-137.009995,-93.349998,-145.130005,-155.830002,-124.650002,-123.250000,-127.709999,-169.759995,-68.489998,-117.669998,-69.239998,-115.309998,-123.860001,65.010002
9996,-152.169998,-161.449997,-173.210007,-165.320007,-143.570007,-124.150002,-127.339996,-87.309998,-160.919998,-158.360001,-121.870003,-129.550003,-121.470001,-120.339996,-68.029999,-135.130005,-105.190002,-114.330002,-121.029999,47.090000
9997,-149.619995,-147.479996,-171.960007,-152.589996,-137.279999,-105.550003,-122.220001,-80.010002,-156.039993,-155.119995,-116.360001,-118.099998,-113.690002,-102.760002,-67.839996,-120.410004,-109.099998,-116.419998,-119.099998,95.589996
9998,-126.860001,-122.889999,-125.879997,-130.339996,-134.779999,-134.350006,-127.080002,-76.739998,-137.649994,-146.800003,-111.720001,-114.199997,-106.739998,-104.699997,-60.240002,-154.119995,-129.639999,-110.029999,-116.239998,72.980003
9999,-131.339996,-153.470001,-168.320007,-155.339996,-123.169998,-82.660004,-122.050003,-77.889999,-148.979996,-149.880005,-112.050003,-112.910004,-102.180000,-71.809998,-56.290001,-133.979996,-148.220001,-108.330002,-114.339996,25.549999

In [5]:
def spg_window(row):
    spg_data = read_spg(row.spectrogram_id)
    spg_offset = int(row.spectrogram_label_offset_seconds)
    spg = spg_data.loc[(spg_data.time >= spg_offset) & (spg_data.time < spg_offset + 600)]
    spg = spg.drop(columns=['time'])
    return spg

spg_window(train_csv.iloc[0]).iloc[142:147]

,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,LL_2.34,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
142,4.86,5.32,6.45,6.560000,5.19,5.16,9.110000,14.180000,10.60,11.630000,...,0.22,0.16,0.14,0.14,0.12,0.10,0.15,0.19,0.27,0.46
143,7.61,10.67,14.49,13.660000,11.09,9.34,13.840000,13.980000,14.08,16.969999,...,0.13,0.19,0.20,0.18,0.21,0.18,0.15,0.15,0.29,0.44
144,5.66,9.55,16.73,16.299999,13.72,19.07,11.300000,13.480000,15.11,15.890000,...,0.23,0.24,0.19,0.17,0.17,0.16,0.23,0.27,0.27,0.23
145,4.16,3.90,5.50,7.180000,10.09,16.67,16.450001,19.700001,20.91,15.380000,...,0.14,0.14,0.14,0.14,0.16,0.25,0.28,0.28,0.28,0.19
146,3.39,4.59,5.64,7.580000,9.07,13.00,22.280001,30.650000,29.84,28.660000,...,0.21,0.17,0.15,0.08,0.11,0.11,0.11,0.12,0.08,0.08

In [6]:
df = eeg_window(train_csv.iloc[0]).iloc[400:600].mean(axis=0)
df.index = [f'{c}_mean_{0}' for c in df.index]
df

Fp1_mean_0    -92.532097
F3_mean_0    -103.000450
C3_mean_0    -108.314499
P3_mean_0    -128.684036
F7_mean_0     -88.587204
T3_mean_0     -97.317497
T5_mean_0    -113.370644
O1_mean_0    -113.210297
Fz_mean_0    -130.212738
Cz_mean_0    -118.097054
Pz_mean_0    -110.957100
Fp2_mean_0   -121.806702
F4_mean_0    -122.186203
C4_mean_0    -145.168610
P4_mean_0    -133.133850
F8_mean_0    -141.297592
T4_mean_0    -109.214256
T6_mean_0    -139.868652
O2_mean_0    -112.462708
EKG_mean_0     11.401050
dtype: float32

In [7]:
def eeg_features(eeg_df, w=1):
    features = []
    # divide the 50s (sampled at 200Hz) window into 5 10s windows, index of the centre (3rd) window = 200*2 = 400 to 600 (excl.)
    for i in range(-w, w + 1):
        df = eeg_df.iloc[(400 + 200 * i):(600 + 200 * i)].mean(axis=0)
        df.index = [f'{label}_mean_{i}' for label in df.index]
        features.append(df) 

        df = eeg_df.iloc[(400 + 200 * i):(600 + 200 * i)].std(axis=0)
        df.index = [f'{label}_std_{i}' for label in df.index]
        features.append(df) 
    return pd.concat(features, axis=0)

# eeg_window(train_csv.iloc[0]).std(axis=0).mean()

# eeg_features(eeg_window(train_csv.iloc[0]))

train_csv.iloc[:10].apply(lambda row: eeg_features(eeg_window(row)), axis=1)

,Fp1_mean_-1,F3_mean_-1,C3_mean_-1,P3_mean_-1,F7_mean_-1,T3_mean_-1,T5_mean_-1,O1_mean_-1,Fz_mean_-1,Cz_mean_-1,...,Pz_std_1,Fp2_std_1,F4_std_1,C4_std_1,P4_std_1,F8_std_1,T4_std_1,T6_std_1,O2_std_1,EKG_std_1
0,-118.054153,-117.892052,-115.492439,-129.675903,-131.569595,-106.295052,-115.780159,-111.079002,-128.966095,-113.901253,...,19.374907,10.718746,12.126077,16.522017,22.666361,11.374597,10.687311,17.779625,17.438190,218.615585
1,-90.547249,-107.235001,-109.688652,-142.473358,-95.875801,-107.319801,-122.266800,-112.238350,-134.732697,-115.991699,...,14.107919,16.816469,17.521824,18.810585,19.795387,18.192183,16.751495,21.117636,9.898705,220.871262
2,-128.822891,-131.113846,-123.310898,-144.922241,-163.651352,-122.650703,-124.133499,-107.664093,-135.563553,-115.556297,...,17.017540,19.756502,22.097664,24.063030,24.683544,28.075340,21.580967,20.510815,11.093168,221.897705
3,-125.087448,-132.386292,-126.103302,-144.820053,-142.547699,-114.087051,-120.812698,-118.926857,-152.990753,-127.743401,...,26.824158,28.870182,22.417116,24.440929,35.029133,29.399618,28.369846,33.202175,24.573303,227.052734
4,-132.108597,-127.352051,-117.975647,-139.534195,-159.671997,-112.185158,-117.836647,-122.002594,-141.381760,-119.356941,...,13.038032,21.001163,19.271564,17.937460,20.514135,20.065237,16.820429,17.914148,9.609157,229.543472
5,-126.633347,-126.674500,-121.227303,-142.039047,-149.258850,-115.973701,-120.294044,-120.509392,-150.162155,-117.480400,...,15.205322,23.426414,23.890882,22.202187,32.339317,20.309427,21.181570,26.660414,13.925936,232.170700
6,-106.735641,-116.901306,-118.841797,-132.401749,-132.792007,-113.523750,-115.717949,-139.454041,-259.348999,-118.038094,...,22.263861,18.737663,20.081175,29.106428,26.830502,18.034994,23.117016,24.123316,14.660709,237.198044
7,-83.580803,-88.459854,-103.022697,-96.644745,-129.045746,-92.323753,-91.155998,-185.520004,-331.396576,-182.115738,...,23.236814,22.144922,24.506165,33.434036,31.190575,20.697226,31.271320,30.536253,17.348383,171.016006
8,-117.524101,-118.606201,-129.004105,-132.271194,-140.333160,-100.534645,-104.283005,-171.908356,-278.082611,-202.397690,...,25.123409,20.836134,28.030737,39.006592,32.927361,22.670023,34.759705,31.521866,18.733501,228.574631
9,-13.491600,-6.864450,21.842600,4.874100,-2.700500,1.159200,20.304001,24.436899,-18.822849,-3.767300,...,15.736202,12.595120,14.438226,17.379230,15.729625,12.177394,4.989801,8.148358,10.688300,21.218210

In [8]:
def spg_features(spg_df, w=1):
    features = []
    # divide the 600s window into 10s windows from the centre, and 2 5s windows on either side, the centre one (295s to 305s) has index (295-1)/2 = 147 to 152 (excl.)
    for i in range(-w, w + 1):
        df = spg_df.iloc[(147 + 5 * i):(152 + 5 * i)].mean(axis=0)
        df.index = [f'{label}_mean_{i}' for label in df.index]
        features.append(df) 

        df = spg_df.iloc[(147 + 5 * i):(152 + 5 * i)].std(axis=0)
        df.index = [f'{label}_std_{i}' for label in df.index]
        features.append(df) 
    return pd.concat(features, axis=0)

# spg_window(train_csv.iloc[0]).std(axis=0).mean()

# spg_features(spg_window(train_csv.iloc[0]))

train_csv.iloc[256:259].apply(lambda row: spg_features(spg_window(row)), axis=1)

,LL_0.59_mean_-1,LL_0.78_mean_-1,LL_0.98_mean_-1,LL_1.17_mean_-1,LL_1.37_mean_-1,LL_1.56_mean_-1,LL_1.76_mean_-1,LL_1.95_mean_-1,LL_2.15_mean_-1,LL_2.34_mean_-1,...,RP_18.16_std_1,RP_18.36_std_1,RP_18.55_std_1,RP_18.75_std_1,RP_18.95_std_1,RP_19.14_std_1,RP_19.34_std_1,RP_19.53_std_1,RP_19.73_std_1,RP_19.92_std_1
256,52.788002,57.094006,69.412003,76.848007,79.120003,100.314003,112.058006,123.573997,111.403992,93.438004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,47.602001,61.954002,83.307999,106.800003,118.823997,133.714005,122.722000,108.545998,85.102005,67.288002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,40.126003,54.909996,86.278000,122.304001,140.556000,153.147995,133.230011,96.918007,68.162003,59.852001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Example of NaNs in raw data

train_csv.iloc[256:259]

pd.read_parquet(f'data/train_spectrograms/{train_csv.iloc[256].spectrogram_id}.parquet').iloc[170:180]

,time,LL_0.59,LL_0.78,LL_0.98,LL_1.17,LL_1.37,LL_1.56,LL_1.76,LL_1.95,LL_2.15,...,RP_18.16,RP_18.36,RP_18.55,RP_18.75,RP_18.95,RP_19.14,RP_19.34,RP_19.53,RP_19.73,RP_19.92
170,341,66.430000,70.080002,115.089996,101.849998,107.839996,136.889999,111.959999,115.010002,79.309998,...,0.79,0.78,0.90,0.58,0.41,0.43,0.73,0.80,0.82,0.86
171,343,17.660000,52.090000,55.070000,94.610001,105.809998,76.220001,64.790001,51.369999,28.070000,...,0.96,0.90,0.88,0.79,0.72,0.60,0.71,0.68,0.87,0.73
172,345,30.770000,59.889999,112.000000,154.389999,166.550003,163.259995,97.080002,51.939999,28.450001,...,0.90,0.84,0.82,0.40,0.80,0.87,0.90,0.87,0.65,0.63
173,347,11.940000,12.860000,58.639999,135.259995,156.429993,160.270004,147.300003,51.330002,27.190001,...,1.15,1.23,0.81,0.58,0.42,0.60,0.81,0.73,0.69,0.56
174,349,165.220001,228.190002,265.929993,284.350006,270.809998,205.300003,176.279999,126.639999,116.639999,...,1.23,1.04,0.69,0.59,0.48,0.46,0.74,0.79,0.73,0.70
175,351,291.980011,321.059998,419.470001,320.529999,223.350006,211.839996,150.179993,142.380005,161.149994,...,0.61,0.86,0.53,0.83,0.47,0.37,0.46,0.30,0.60,0.41
176,353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
features_eeg = train_csv.apply(lambda row: eeg_features(eeg_window(row)), axis=1)
features_eeg

,Fp1_mean_-1,F3_mean_-1,C3_mean_-1,P3_mean_-1,F7_mean_-1,T3_mean_-1,T5_mean_-1,O1_mean_-1,Fz_mean_-1,Cz_mean_-1,...,Pz_std_1,Fp2_std_1,F4_std_1,C4_std_1,P4_std_1,F8_std_1,T4_std_1,T6_std_1,O2_std_1,EKG_std_1
0,-118.054153,-117.892052,-115.492439,-129.675903,-131.569595,-106.295052,-115.780159,-111.079002,-128.966095,-113.901253,...,19.374907,10.718746,12.126077,16.522017,22.666361,11.374597,10.687311,17.779625,17.438190,218.615585
1,-90.547249,-107.235001,-109.688652,-142.473358,-95.875801,-107.319801,-122.266800,-112.238350,-134.732697,-115.991699,...,14.107919,16.816469,17.521824,18.810585,19.795387,18.192183,16.751495,21.117636,9.898705,220.871262
2,-128.822891,-131.113846,-123.310898,-144.922241,-163.651352,-122.650703,-124.133499,-107.664093,-135.563553,-115.556297,...,17.017540,19.756502,22.097664,24.063030,24.683544,28.075340,21.580967,20.510815,11.093168,221.897705
3,-125.087448,-132.386292,-126.103302,-144.820053,-142.547699,-114.087051,-120.812698,-118.926857,-152.990753,-127.743401,...,26.824158,28.870182,22.417116,24.440929,35.029133,29.399618,28.369846,33.202175,24.573303,227.052734
4,-132.108597,-127.352051,-117.975647,-139.534195,-159.671997,-112.185158,-117.836647,-122.002594,-141.381760,-119.356941,...,13.038032,21.001163,19.271564,17.937460,20.514135,20.065237,16.820429,17.914148,9.609157,229.543472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106795,-43.204750,-24.642952,0.423900,-18.577648,4.382650,-17.014502,-21.298800,-30.606949,-4.556201,-34.619099,...,23.816084,22.634747,17.639456,19.606722,21.348986,26.215918,19.219349,18.924036,22.221233,9.125668
106796,-34.002350,-34.817650,-11.502851,-32.254749,-9.410399,-30.830952,-37.683151,-45.043602,4.050700,-34.956600,...,27.165335,43.670696,15.571518,22.584576,27.163719,23.589273,25.563711,26.144827,27.830446,9.264424
106797,12.882051,-25.974848,-4.719850,-31.644951,10.923949,-19.172050,-44.217804,-57.268501,20.545649,-43.883400,...,17.124174,21.565754,14.132894,14.376186,16.430014,18.203133,15.004237,14.369315,15.074677,9.079716
106798,-76.676498,-36.319103,-6.510350,-19.231699,-28.068100,-26.531450,-28.429199,-29.806999,-2.521300,-34.711952,...,27.213554,50.331459,16.062458,19.693455,25.024834,46.459652,23.706312,26.960976,26.008408,9.105057
106799,-48.996498,-15.943500,15.624551,4.516650,2.711751,-5.000150,-7.284701,-10.004850,-17.726049,-22.636799,...,14.374599,27.968037,10.646491,12.825237,15.160320,21.418756,16.030758,16.119583,16.971779,9.210934

In [22]:
features_spg = train_csv.apply(lambda row: spg_features(spg_window(row)), axis=1)
features_spg

,LL_0.59_mean_-1,LL_0.78_mean_-1,LL_0.98_mean_-1,LL_1.17_mean_-1,LL_1.37_mean_-1,LL_1.56_mean_-1,LL_1.76_mean_-1,LL_1.95_mean_-1,LL_2.15_mean_-1,LL_2.34_mean_-1,...,RP_18.16_std_1,RP_18.36_std_1,RP_18.55_std_1,RP_18.75_std_1,RP_18.95_std_1,RP_19.14_std_1,RP_19.34_std_1,RP_19.53_std_1,RP_19.73_std_1,RP_19.92_std_1
0,5.136,6.806000,9.761999,10.256000,9.832000,12.648000,14.596001,18.397999,18.108000,17.705999,...,0.586813,0.565358,0.708400,0.744426,0.856960,0.725927,0.753877,0.656833,0.741876,0.703470
1,7.030,9.020000,10.353999,10.634001,12.672000,16.341999,19.212000,23.872000,24.288000,19.420000,...,0.580620,0.361842,0.520019,0.662571,0.723830,0.659037,0.761295,0.232981,0.357980,0.492423
2,7.100,10.072001,11.745999,12.862000,13.895999,18.026001,20.002001,23.956001,24.427999,19.614000,...,0.508940,0.361012,0.438315,0.602852,0.380854,0.587597,0.840077,0.271514,0.267339,0.614589
3,4.788,6.578000,8.612000,9.686000,11.950000,13.089999,14.598001,15.548001,15.430002,13.273999,...,0.940356,0.407026,0.552992,0.608876,0.422694,0.461541,0.242837,0.686826,0.904505,0.427633
4,6.870,9.352000,11.086000,12.539999,12.972000,14.359999,15.074000,17.189999,18.740000,17.278000,...,1.010149,1.555516,1.638176,1.822490,0.803791,0.611204,0.525424,0.862862,0.733757,0.920147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106795,13.912,17.396000,35.627998,42.721996,44.560001,39.973999,28.978001,14.918001,9.602000,8.567999,...,0.013038,0.025495,0.021909,0.043012,0.033466,0.027019,0.026077,0.020494,0.015811,0.021679
106796,11.264,14.441999,28.675999,32.605999,34.174000,30.694000,20.450001,11.954000,8.354000,7.678000,...,0.008367,0.013038,0.021909,0.040373,0.023875,0.028810,0.026077,0.018166,0.015811,0.023452
106797,9.222,12.217999,25.362000,29.340000,30.026001,27.939999,18.865999,9.608000,7.596001,6.594000,...,0.016432,0.018166,0.013416,0.019235,0.020736,0.016432,0.005477,0.013038,0.024083,0.023452
106798,8.932,12.191999,24.743999,24.745998,25.472000,25.137999,14.585999,8.264000,7.350000,5.726000,...,0.019235,0.015811,0.013416,0.019235,0.032094,0.023875,0.008367,0.013416,0.020736,0.020736
106799,9.464,12.257999,21.567999,20.736000,22.242001,20.626001,12.668000,8.080000,6.486000,5.392000,...,0.020000,0.017889,0.016432,0.020736,0.032094,0.022361,0.014832,0.011402,0.017889,0.016733

In [23]:
y = train_csv[train_csv.columns[-6:]]
y = y.div(y.sum(axis=1), axis=0)

In [24]:
from sklearn.preprocessing import StandardScaler

col_features = list(features_spg.columns) + list(features_eeg.columns)
col_targets = list(y.columns)

train = train_csv.drop(columns=col_targets)
train = pd.concat([train, features_spg, features_eeg, y], axis=1)
train = train.dropna()
train = train.reset_index()

std_scaler = StandardScaler()

train[col_features] = std_scaler.fit_transform(train[col_features])

train

,index,eeg_id,eeg_sub_id,eeg_label_offset_seconds,spectrogram_id,spectrogram_sub_id,spectrogram_label_offset_seconds,label_id,patient_id,expert_consensus,...,T4_std_1,T6_std_1,O2_std_1,EKG_std_1,seizure_vote,lpd_vote,gpd_vote,lrda_vote,grda_vote,other_vote
0,0,1628180742,0,0.0,353733,0,0.0,127492639,42516,Seizure,...,-0.153985,-0.137193,-0.136728,-0.060652,1.0,0.0,0.0,0.0,0.0,0.0
1,1,1628180742,1,6.0,353733,1,6.0,3887563113,42516,Seizure,...,-0.143799,-0.131494,-0.147828,-0.060472,1.0,0.0,0.0,0.0,0.0,0.0
2,2,1628180742,2,8.0,353733,2,8.0,1142670488,42516,Seizure,...,-0.135686,-0.132530,-0.146070,-0.060390,1.0,0.0,0.0,0.0,0.0,0.0
3,3,1628180742,3,18.0,353733,3,18.0,2718991173,42516,Seizure,...,-0.124282,-0.110864,-0.126224,-0.059978,1.0,0.0,0.0,0.0,0.0,0.0
4,4,1628180742,4,24.0,353733,4,24.0,3080632009,42516,Seizure,...,-0.143683,-0.136963,-0.148254,-0.059778,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106482,106795,351917269,6,12.0,2147388374,6,12.0,4195677307,10351,LRDA,...,-0.139653,-0.135239,-0.129687,-0.077403,0.0,0.0,0.0,1.0,0.0,0.0
106483,106796,351917269,7,14.0,2147388374,7,14.0,290896675,10351,LRDA,...,-0.128996,-0.122912,-0.121429,-0.077392,0.0,0.0,0.0,1.0,0.0,0.0
106484,106797,351917269,8,16.0,2147388374,8,16.0,461435451,10351,LRDA,...,-0.146734,-0.143015,-0.140208,-0.077407,0.0,0.0,0.0,1.0,0.0,0.0
106485,106798,351917269,9,18.0,2147388374,9,18.0,3786213131,10351,LRDA,...,-0.132116,-0.121519,-0.124111,-0.077405,0.0,0.0,0.0,1.0,0.0,0.0
106486,106799,351917269,10,20.0,2147388374,10,20.0,3642716176,10351,LRDA,...,-0.145009,-0.140027,-0.137415,-0.077396,0.0,0.0,0.0,1.0,0.0,0.0

In [25]:
import os
os.environ["KERAS_BACKEND"] = "torch"
import keras

In [61]:
from sklearn.model_selection import GroupKFold

keras.utils.set_random_seed(42)

n_classes = 6

all_oof = []
all_true = []

group_k_fold = GroupKFold(n_splits=5)
for train_ids, valid_ids in group_k_fold.split(train, None, train.patient_id):
    model = keras.Sequential([
        keras.layers.Dense(256, activation=keras.activations.relu),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(128, activation=keras.activations.relu),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(64, activation=keras.activations.relu),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(32, activation=keras.activations.relu),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(16, activation=keras.activations.relu),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(n_classes, activation=keras.activations.softmax)
    ])

    model.compile(optimizer=keras.optimizers.Adam(),
                loss=keras.losses.CategoricalCrossentropy(),
                metrics=[keras.metrics.MeanAbsoluteError()])
    
    X_train = train.loc[train_ids, col_features]
    y_train = train.loc[train_ids, col_targets]
    X_valid = train.loc[valid_ids, col_features]
    y_valid = train.loc[valid_ids, col_targets]

    model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_valid, y_valid))

    all_oof.append(model.predict(X_valid))
    all_true.append(y_valid)
    
    break


all_oof = np.concatenate(all_oof)
all_true = np.concatenate(all_true)

from kaggle_kl_div import score

df_oof = pd.DataFrame(all_oof.copy())
df_oof['id'] = np.arange(len(df_oof))

df_true = pd.DataFrame(all_true.copy())
df_true['id'] = np.arange(len(df_true))

score(solution=df_true, submission=df_oof, row_id_column_name='id')

Epoch 1/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.9958 - mean_absolute_error: 0.2358 - val_loss: 1.9124 - val_mean_absolute_error: 0.2354
Epoch 2/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 1.9098 - mean_absolute_error: 0.2344 - val_loss: 1.8889 - val_mean_absolute_error: 0.2353
Epoch 3/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 1.8913 - mean_absolute_error: 0.2349 - val_loss: 1.8772 - val_mean_absolute_error: 0.2348
Epoch 4/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8608 - mean_absolute_error: 0.2349 - val_loss: 1.8569 - val_mean_absolute_error: 0.2355
Epoch 5/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8365 - mean_absolute_error: 0.2352 - val_loss: 1.8753 - val_mean_absolute_error: 0.2340
Epoch 6/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8533 - mean_absolute_error: 0.2350 - val_loss: 1.8750 - val_mean_absolute_error: 0.2349
Epoch 7/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 1.8483 - mean_absolute_error: 0.2350 - val_loss: 1.8866 - val_mean_absolute_error: 0.2347
Epoch 8/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8504 - mean_absolute_error: 0.2351 - val_loss: 1.8758 - val_mean_absolute_error: 0.2347
Epoch 9/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8388 - mean_absolute_error: 0.2350 - val_loss: 1.9094 - val_mean_absolute_error: 0.2352
Epoch 10/10
2663/2663 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 1.8603 - mean_absolute_error: 0.2351 - val_loss: 1.9051 - val_mean_absolute_error: 0.2350
666/666 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

1.690534858542378

In [39]:
df_equal = pd.DataFrame(np.ones(df_oof.shape) / 6)
df_equal['id'] = np.arange(len(df_equal))

df_true = pd.DataFrame(all_true.copy())
df_true['id'] = np.arange(len(df_true))

score(solution=df_true, submission=df_equal, row_id_column_name='id')

1.400184048509199